#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# This example catches duplicate Signed-off-by lines.

# test "" = "$(grep '^Signed-off-by: ' "$1" |
# 	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
# 	echo >&2 Duplicate Signed-off-by lines.
# 	exit 1
# }

# PluginInfo = {
#     Name = "Compile Test 4",
#     Version = "0.0.0.3",
#     Id = "COMPILEDPLUGINTEST",
#     Description = "Compiled from Visual Studio Code",
#     ShowDebug = false
# }

# oldnum=`cut -d ',' -f2 file1.txt`  
# newnum=`expr $oldnum + 1`
# sed -i "s/$oldnum\$/$newnum/g" file1.txt 

echo "$1"

oldnum="$( grep 'Version' info.lua | cut -d $'\"' -f2 | cut -d $'\"' -f1 )"
echo $oldnum
newnum="$oldnum"

if grep -Fq "<ver_maj>" "$1"
then
  echo "updating version major num"

  majnum=${oldnum:0:1}
  ((majnum++))
  newnum="$majnum.0.0.0"

elif grep -Fq "<ver_min>" "$1"
then
  echo "updating version minor num"

  minnum=${oldnum:2:1}
  ((minnum++))
  newnum="${oldnum:0:1}.$minnum.0.0"

elif grep -Fq "<ver_fix>" "$1"
then
  echo "updating version fix num"

  fixnum=${oldnum:4:1}
  ((fixnum++))
  newnum="${oldnum:0:3}.$fixnum.0"

elif grep -Fq "<ver_dev>" "$1"
then
  echo "updating version dev num"

  devnum=${oldnum:6:1}
  ((devnum++))
  newnum="${oldnum%.*}.$devnum"

else
  echo "updating version dev num"

  devnum=${oldnum:6:1}
  ((devnum++))
  newnum="${oldnum%.*}.$devnum"

fi

echo $newnum
sed -i "s/$oldnum\$/$newnum/g" info.lua
echo "$(grep 'Version' info.lua)"